apiVersion: v1
kind: Service
metadata:
  name: alglab444
  labels:
    app: stack-alglab444
spec:
  type: LoadBalancer
  selector:
    app: stack-alglab444
  ports:

    - port: 80
      targetPort: 6901
      protocol: TCP
      name: http

    - port: 5901
      targetPort: 5901
      protocol: TCP
      name: vnc

#     - port: 81
#       targetPort: 6902
#       protocol: TCP
#       name: http2

#     - port: 5902
#       targetPort: 5902
#       protocol: TCP
#       name: vnc2

#     - port: 4100
#       targetPort: 4100
#       protocol: TCP
#       name: ibg

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: alglab444
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stack-alglab444
    spec:
      containers:

        - name: vnc-web-proxy
          image: appsoa/docker-centos-desktop-webvnc:latest
          ports:
            - containerPort: 6901
              hostPort: 6901
          env:
            - name: CONF_VNC_HTTP_PORT
              value: '6901'
            - name: CONF_VNC_REMOTE
              value: 'alglab444:5901'


        - name: algolab-desktop
          image: appsoa/docker-centos-desktop-algolab:latest
          ports:
            - containerPort: 5901
              hostPort: 5901
          env:
            - name: CONF_IB_GATEWAY
              value: 'alglab444:4100'


        - name: ibgateway-desktop
          image: appsoa/docker-centos-desktop-ibgateway:latest
          ports:
            - containerPort: 5902
              hostPort: 5902
            - containerPort: 4100
              hostPort: 4100
          env:
            - name: CONF_VNC_PASS
              value: 'testing123'
            - name: CONF_CONTROLLER_PORT
              value: '4200'
            - name: CONF_API_PORT
              value: '4100'
            - name: CONF_TRADING_MODE
              value: 'paper'
            - name: CONF_IB_USER
              value: 'alglab444'
            - name: CONF_IB_PASS
              value: 'greg2017'
            - name: CONF_IB_READ_ONLY
              value: 'no'

        # - name: ibgateway-webvnc
        #   image: appsoa/docker-centos-desktop-webvnc:latest
        #   ports:
        #     - containerPort: 6902
        #       hostPort: 6902
        #   env:
        #     - name: CONF_VNC_HTTP_PORT
        #       value: '6902'
        #     - name: CONF_VNC_REMOTE
        #       value: 'svc-alglab444:5902'



# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: webvnc
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: ibgateway
#     spec:
#       containers:
#       - name: webvnc
#         image: appsoa/docker-centos-desktop-webvnc:latest
#         ports:
#           - containerPort: 6901
#         env:
#           - name: CONF_VNC_HTTP_PORT
#             value: '6901'
#           - name: CONF_VNC_REMOTE
#             value: 'http-to-webvnc:5901'


---

# kind: Service
# apiVersion: v1
# metadata:
#   name: ibgateway-vnc
#   labels:
#     app: ibgateway-vnc
# spec:
#   type: NodePort
#   ports:
#   - port: 5901
#     targetPort: 5901
#     protocol: TCP
#     name: ibgateway-vnc
#   selector:
#     app: ibgateway

# ---

#   kind: Ingress
#   apiVersion: extensions/v1beta1
#   metadata:
#     name: http-to-webvnc
#   spec:
#     backend:
#       serviceName: http-to-webvnc
#       servicePort: 80

# # ---


# apiVersion: v1
# kind: Service
# metadata:
#   name: desktop-gateway
#   labels:
#     component: gateway
#     service: vncserver
# spec:
#   type: LoadBalancer
#   selector:
#     service: vncserver
#   ports:
#     - port: 6901
#       targetPort: 6901
#       protocol: TCP
#       name: webvnc
#     - port: 6902
#       targetPort: 6902
#       protocol: TCP
#       name: webvnc2
#     - port: 5901
#       targetPort: 5901
#       protocol: TCP
#       name: vnc
#     - port: 5902
#       targetPort: 5902
#       protocol: TCP
#       name: vnc2