apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alglab111
  namespace: algolab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: algolab-desktop
    spec:
      containers:
      # - name: algolab-webvnc
      #   image: appsoa/docker-centos-desktop-algolab:latest
      #   ports:
      #   - containerPort: 6901
      #   env:
      #   - name: CONF_VNC_HTTP_PORT
      #     value: "6901"
      #   - name: CONF_VNC_REMOTE
      #     value: "127.0.0.1:5902"
      #   resources:
      #     limits:
      #       cpu: 200m
      #       memory: 100Mi
      - name: algolab-desktop
        image: appsoa/docker-centos-desktop-algolab:latest
        ports:
        - containerPort: 5901
        volumeMounts:
        - mountPath: /home/user/Desktop/AlgoLab/Prefs
          name: algolab-user-alglab111
        env:
        - name: CONF_VNC_PASS
          value: "greg2017"
        - name: CONF_CONTROLLER_PORT
          value: "4440"
        - name: CONF_API_PORT
          value: "4100"
        - name: CONF_TRADING_MODE
          value: "paper"
        - name: CONF_IB_USER
          value: "alglab111"
        - name: CONF_IB_PASS
          value: "greg2017"
        - name: CONF_IB_GATEWAY
          value: "127.0.0.1:4100"
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
      volumes:
      - name: algolab-user-alglab111
        gcePersistentDisk:
          pdName: algolab-user-alglab111
          fsType: ext4