                                         __                    
#                                        /\ \__                 
#     __  __    ___     ___ ___      __  \ \ ,_\    __    ___   
#    /\ \/\ \  / __`\ /' __` __`\  /'__`\ \ \ \/  /'__`\ / __`\ 
#    \ \ \_\ \/\ \L\ \/\ \/\ \/\ \/\ \L\.\_\ \ \_/\  __//\ \L\ \
#     \/`____ \ \____/\ \_\ \_\ \_\ \__/.\_\\ \__\ \____\ \____/
#      `/___/> \/___/  \/_/\/_/\/_/\/__/\/_/ \/__/\/____/\/___/ 
#         /\___/                                                
#         \/__/                                                 

---
apiVersion: extensions/v1beta1
#
kind: Deployment
metadata:
  name: alglab111
  namespace: algolab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: desktop
    spec:
      containers:
      # - name: ibgateway
      #   image: appsoa/docker-centos-desktop-ibgateway:latest
      #   ports:
      #   - containerPort: 5902
      #   env:
      #   # - name: CONF_VNC_HTTP_PORT
      #   #   value: "6902"
      #   # - name: CONF_VNC_REMOTE
      #   #   value: "127.0.0.1:5902"
      #   - name: CONF_VNC_PASS
      #     value: "greg2017"
      #   - name: CONF_CONTROLLER_PORT
      #     value: "4440"
      #   - name: CONF_API_PORT
      #     value: "4100"
      #   - name: CONF_TRADING_MODE
      #     value: "paper"
      #   - name: CONF_IB_USER
      #     value: "alglab111"
      #   - name: CONF_IB_PASS
      #     value: "greg2017"
      #   - name: CONF_IB_GATEWAY
      #     value: "127.0.0.1:4100"
      #   resources:
      #     limits:
      #       cpu: 300m
      #       memory: 200Mi
            
      - name: algolab-desktop
        image: appsoa/docker-centos-desktop-algolab:latest
        ports:
        - containerPort: 7000
        - containerPort: 5901
        volumeMounts:
        - mountPath: /home/user/Desktop/AlgoLab/Prefs
          name: algolab-user-alglab111
        env:
        - name: CONF_VNC_HTTP_PORT
          value: "7000"
        - name: CONF_VNC_REMOTE
          value: "127.0.0.1:5901"
        - name: CONF_VNC_PASS
          value: "greg2017"
        - name: CONF_CONTROLLER_PORT
          value: "4440"
        - name: CONF_API_PORT
          value: "4100"
        - name: CONF_TRADING_MODE
          value: "paper"
        - name: CONF_IB_USER
          value: "alglab111"
        - name: CONF_IB_PASS
          value: "greg2017"
        - name: CONF_IB_GATEWAY
          value: "127.0.0.1:4100"
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
      volumes:
      - name: algolab-user-alglab111
        gcePersistentDisk:
          pdName: algolab-user-alglab111
          fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: algolab111-svc
  namespace: algolab
spec:
  type: LoadBalancer
  selector:
    app: desktop
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: webvnc
    - protocol: TCP
      port: 5901
      targetPort: 5901
      name: vnc