---
  kind: Service
  apiVersion: v1
  metadata:
    name: algolab111-svc
    namespace: algolab
  spec:
    type: LoadBalancer
    selector:
      app: algolab-desktop
    ports:
      - protocol: TCP
        port: 6901
        targetPort: 6901
        name: webvnc
      - protocol: TCP
        port: 6902
        targetPort: 6902
        name: vnc