apiVersion: v1
kind: Service
metadata:
  name: deployments-alglab111
  labels:
    app: workstation
spec:
  selector:
    app: workstation
  type:
    LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 6901
    targetPort: 6901
    name: asdf
  - port: 6999
    targetPort: 6999
    name: tsrtg